### PR TITLE
Parsing date like May,21st.2015

### PR DESCRIPTION
**Pull request by felipevolpone**
I created an different method called from_str to parse this type of date. Also, this method is linked in the main function of BaseParser. 

You can see the change that I did in the old "parse_diff" method to call all methods that could try parse the value (from_str and parse_diff). This could be simpler if the method parse_diff doesn't exists, but I didn't removed cause I don't where you could use (I checked the tests and no one call it).

Anyway, if it's something wrong please tell me.
Tks

### CODE REVIEW

**Comment by shinux** [comment]
Hi, @felipevolpone ,seems that trasvis-ci shows your pull request built failed. you can see them in Details.

`except Exception, e` does not exist in Python3, should be replace with `except Exception as e`, and other error you can check them in travis details.

**Comment by felipevolpone** [comment]
Hey @shnode I'll check. Actually, I was using Python 2.7, so I'll change what is necessary.
tks

**Comment by felipevolpone** [comment]
@shnode  It's done! :)

**Comment by shinux** [comment]
fixed #1

**Pull request merged**
